### ISSUE TITLE
No data in Feature Info window.

### ISSUE THREAD

**Issue by pawelon** [qgis/qwc2-demo-app#130]
Hi, the wms map shows perfectly ok, but when I click on the feature associated with some metdata, the Feature Info window shows up with "No information available for the selected point". The explicit request sends correct xml response:

`
<GetFeatureInfoResponse><Layer name="tt"><Feature id="1"><Attribute value="22" name="id"/><Attribute value="rr" name="test"/><BoundingBox maxy="4745088.7679262497" maxx="3999373.3245019447" minx="3902101.0088548195" miny="4708648.3838167517" CRS="EPSG:3857"/><Attribute type="derived" value="MultiPolygon (((3960581.9478692543 4745088.7679262497, 3999373.3245019447 4727750.1980676996, 3964402.3107194435 4708648.3838167517, 3902101.0088548195 4722460.4648905126, 3960581.9478692543 4745088.7679262497)))" name="geometry"/></Feature></Layer><Layer name="003-mac-pro"/><Layer name="003"/><Layer name="cpk_-1"/><Layer name="obrys-1"/></GetFeatureInfoResponse>`

Is there any special steps required for configuring the feature info handler?

**Comment by manisandro** [comment]
The request is likely getting blocked by the browser due to cross-resource-sharing policy (you should be able to see corresponding messages in the browser console, F12 on firefox/chrome). In this case, you either need to tell your webserver to send the allow-origin headers with the response, or have the application run on the same origin as the qgis server, or use a proxy server which adds the allow-origin headers. If you are only running the application on a different origin than qgis server for development purposes, there are various plugins for chrome/firefox which allow to inject allow-origin headers for specified origins.

**Comment by pawelon** [comment]
Added 

`Header set Access-Control-Allow-Origin "*"`

to my apache config file. Now works like a charm. Thank you!
