### ISSUE TITLE
SearchProvider: pass the currently active layers

### ISSUE THREAD

**Issue by lucamanga** [qgis/qwc2-demo-app#216]
Hello, 
it would be useful to pass to the search provider function the currently active layers, i.e., in SearchOptions parameter. For example, extending the searchProvider.js example:

```
function coordinatesSearch(text, requestId, searchOptions, dispatch) {
    let displaycrs = searchOptions.displaycrs || "EPSG:4326";
    let activeLayers = searchOptions.activelayers;
    ...
```

So I can instruct the search web service to search in those layers.

**Comment by manisandro** [comment]
Actually state is already passed as last argument to `onSearch`, after `dispatch`. I've added this to the documentation header in `SearchProviders.js`.

**Comment by w0pr** [comment]
> Actually state is already passed as last argument to `onSearch`, after `dispatch`. I've added this to the documentation header in `SearchProviders.js`.

I am a bit confused, since there isn't a documentation header for additional state parameter in [SearchProviders.js](https://github.com/qgis/qwc2-demo-app/blob/master/js/SearchProviders.js).

Obviously the signature of onSearch() function changed, but now there is only searchParams for additional setting from config file; I also need the currently active layers, but would want to get them dynamically.
