### ISSUE TITLE
Print drawing features and delete the feature after reuse the tool

### ISSUE THREAD

**Issue by tomep** [qgis/qwc2-demo-app#22]
Hi developers
i have installed the new qwc2 -> verry good job;-)
i test the new tool -> drawing.
I wanted to print the drawing. the result was e map without the drawing.
![1printoverview](https://cloud.githubusercontent.com/assets/26709746/24354135/078190b8-12f1-11e7-999a-f869a068a081.JPG)
![2print](https://cloud.githubusercontent.com/assets/26709746/24354134/077fcb7a-12f1-11e7-9df3-8145cb425b5a.JPG)

...and after reuse the drawing tool (leave menu, and go in again) the features i created befor, it is not possible to change the color and are not able to delete. I can only change the form and can move it.

regards
tom

**Comment by andreasneumann** [comment]
Hi Tom,

Since I see that you use the Zug example, I will add some information:

- The Zug example is not always at the newest version
- The drawing components have been added just recently and are still under heavy development
- the drawing components are developed by company invit in Sweden
- QGIS server will need some improvements for being able to print the drawings on top of a map.

So you have to be a bit patient regarding the drawing tools.

Andreas

**Comment by tomep** [comment]
hi andreas
thank you for the answer.
i see the drawing tools on zug-example today an see, that the issue (color regulator) i tell you on mailroute on friday ist implemented. so i mean i goes verry fast;-)
no problem, the drawingtool i not the number one of use that i have on qwc2;-)
tom

**Comment by manisandro** [comment]
The new redlining component supports printing, and allows editing drawn features and deleting them.
