### ISSUE TITLE
Broken widget handling

### ISSUE THREAD

**Issue by stamogis** [qgis/qwc2-demo-app#280]
The widget handling on mobile (touch) devices is broken since one of the last updates in June. For example in the feature info window it is no longer possible to scroll or to close the window. On desktop computer everything is working.

**Comment by tudorbarascu** [comment]
Hi,

It may be due to this being upgraded again: https://github.com/qgis/qwc2/pull/124/files

All the best,

Tudor

On Monday, June 28, 2021 12:27 EEST, stamogis ***@***.***> wrote:
 
 
The widget handling on mobile (touch) devices is broken since one of the last updates in June. For example in the feature info window it is no longer possible to scroll or to close the window. On desktop computer everything is working.

**Comment by manisandro** [comment]
Thanks, downgraded again for now
