### ISSUE TITLE
Parse Error in tenantConfig leads to internal server error in QWC Admin

### ISSUE THREAD

**Issue by HeatherHillers** [qgis/qwc2-demo-app#319]
I have a tenantConfig.json that is valid.

I accidentally removed a comma in the tenantConfig, causing a json parse error.

When I opened QWC Admin, I got a 500 Internal Server Error instead of the QWC Admin login screen.

Luckily I found the my error and fixed it, after which the QWC Admin login screen loaded successfully.

But it would be good to have a more descriptive error handling for a json parse error.

**Comment by manisandro** [comment]
I believe this is another issue with the qwc-admin-gui themes plugin, as otherwise the tenantConfig is never read at runtime, but only by the config-generator, which prints out the exception when the tenantConfig is invalid, i.e.

![image](https://user-images.githubusercontent.com/1298852/153158524-9b4c1137-98a6-4429-99fa-e7751a549a34.png)


Please file a new issue at https://github.com/qwc-services/qwc-admin-gui/issues also posting the docker log of the qwc-admin-gui container which should contain a python stack trace.
