### ISSUE TITLE
Connect Qwc2 frontend with qgis server

### ISSUE THREAD

**Issue by fr111** [qgis/qwc2-demo-app#446]
Hello everyone,

I'm starting deploying a qgis server in ubuntu server and I would like to have a good frontend. My qgis server already has a test map that I can see using qgis desktop for windows.
I would like to ask if anyone can help me to connect qwc2 frontend with my qgis server. I already tried to configure the files tenantConfig.json and config.json in ~/qwc-docker/volumes/config-in/default in my qwc2 deployed in linux ubuntu server, but without success. My idea is to have the maps in the qgis server, access them through the qwc2 that I can access through a web browser. I can access the qwc2 using the browser in other machine but I can't see the maps in qgis server.

Thank you for your help.
Regards,
Fábio

**Comment by danceb** [comment]
While this isn't really an issue with the application, there are many configuration steps to take into account. Did you follow the documentation of https://github.com/qwc-services/qwc-docker and the services itself?
You can't "see" maps directly within qgis server, you can access them using GetMap-Requests. Is this what you mean? A good start if something is not visible, is to use the console and network analysis within your browser while loading the application and check for errors there. Besides this you can have a closer look at the logs of your docker containers while running the docker stack with
`docker-compose -f your-docker-compose-file.yml logs -f`.

**Comment by fr111** [comment]
Hello danceb,

thank you for your reply.
O already followed the indications in this link (https://github.com/qwc-services/qwc-docker). I just had a problem with psql: 'psql "service=qwc_configdb" # Config DB' and  'psql "service=qwc_geodb" # Demo data DB' that give me an error in console "psql: error: definition of service "qwc_configdb" not found" and "psql: error: definition of service "qwc_geodb" not found", but the file "pg_service.conf" exists and is equal with the example (https://github.com/qwc-services/qwc-docker/blob/master/pg_service.conf).

I can access http://MyAddress:8088/ and see the map or import others from internet (with qwc2). I access through the browser in other machine but qwc2 is installed in a Linux ubuntu server.

Related with my qgis-server (installed in another Linux server), I can access the url "http://qgis/cgi-bin/qgis_mapserv.fcgi" ang get this:
<ServiceExceptionReport version="1.3.0">
<ServiceException code="Service configuration error">
Service unknown or unsupported. Current supported services (case-sensitive): WMS WFS WCS WMTS SampleService, or use a WFS3 (OGC API Features) endpoint
</ServiceException>
</ServiceExceptionReport>

or access this: http://qgis/cgi-bin/qgis_mapserv.fcgi?SERVICE=WMTS&VERSION=1.3.0&REQUEST=GetCapabilities 
and get:
<Capabilities xsi:schemaLocation="http://www.opengis.net/wmts/1.0 http://schemas.opengis.net/wmts/1.0/wmtsGetCapabilities_response.xsd" version="1.0.0">
<ows:ServiceIdentification>
<ows:ServiceType>OGC WMTS</ows:ServiceType>
<ows:ServiceTypeVersion>1.0.0</ows:ServiceTypeVersion>
<ows:Title>QGIS Server Demo</ows:Title>
<ows:Abstract>
This is a simple World map that showcases QGIS Server capabilities.
</ows:Abstract>
...

I also installed QGIS desktop in a windows machine and can access my map in QGIS-server, I just have to pass the url "http://qgis/cgi-bin/qgis_mapserv.fcgi?VERSION=1.3.0" in connection configurations (in a GUI).

My problem is do the same thing but unless QGIS desktop, use qwc2 web interface.

I can't see errors in console from qwc2, since, I think, everything is ok. I just can't find a place where I need to insert QGIS-server URL (like I did in QGIS-Desktop) to permit qwc2 connect with QGIS-Server.
Can I do some kind of test to check, or what files should I edit to test my connection?

I edited also the files tenantConfig.json and config.json (in ~/qwc-docker/volumes/config-in/default, in qwc2 machine) but probably I edited in the wrong fields. I think the solution will be in this files, but I don't know exactly what I need to edit. 

Thank you for your help.
Regards.

**Comment by danceb** [comment]
> the file "pg_service.conf" exists and is equal with the example

Within the pg_service.conf file you have to configure the credentials of your own postgresql database. So the `host` has to be your host and you have to set up a database, user and password for storing the qwc configuration and you you have to write this within the service definition in `pg_service.conf`. I think you your host is not `qwc-postgis`, so this would not work.

> I can access the url "http://qgis/cgi-bin/qgis_mapserv.fcgi" and get this: Service unknown or unsupported. [...] 

Of course you have to specify a service. WMS/WMTS in the case you want to get a map.

> or access this: http://qgis/cgi-bin/qgis_mapserv.fcgi?SERVICE=WMTS&VERSION=1.3.0&REQUEST=GetCapabilities

To get response from custom QGIS projects you have to define the path of your QGIS project there as well with the `MAP` parameter, see https://docs.qgis.org/3.28/en/docs/server_manual/getting_started.html#serve-a-project

Do you have defined your QGIS server with `"default_qgis_server_url"` in the tenantConfig.json? That's the place where to qwc-config-generator gets the info, where it has to get the Capabilities from. Otherwise this wouldn't work.

Did you have created the configuration files in volumes/config using the qwc-config-generator? Otherwise the map viewer didn't know what to display.

I think the main difficulty is here, that you are using an external QGIS server and not the one from the qwc-services. I really recommend here to use a QGIS server via a docker image as the other services in the same docker stack.

With the configuration in the docker-compose.yml of the `qwc-qgis-server` container, the related nginx configuration,  setting the `"default_qgis_server_url"` correct within the tenantConfig, placing your QGIS projects in the mounted volume (standard is `/volumes/qgs-resources`) you have all configuration at one place. Things like URL rewriting (access a WMS service via http://localhost:8088/wms/yourservice and not http://qgis/cgi-bin/qgis_mapserv.fcgi?MAP=/your/path/to/a/qgisproject) could be handled much better in this way.

**Comment by danceb** [comment]
I think both options are possible. You can use your own QGIS server, then you have to specify the base url with `"default_qgis_server_url"` in the tenantConfig.json, as I mentioned before.

The second option is to use the QGIS server docker image, which is provided by Sourcepole. The related configuration can be found here: https://github.com/qwc-services/qwc-docker/blob/master/docker-compose-example.yml#LL25C1-L31C68
Have a look here for other image versions: https://hub.docker.com/r/sourcepole/qwc-qgis-server/tags

The docker-stack uses the OGC Service, which acts as a proxy which calls the QGIS Server.

Have a look at https://github.com/qwc-services/qwc-docker/blob/master/api-gateway/nginx-example.conf as well.

---
For testing/using the frontend without the docker stack and any services just install an run the qwc2-demo-app:
https://github.com/qgis/qwc2-demo-app

Within https://github.com/qgis/qwc2-demo-app/blob/master/themesConfig.json you can define the themes which point to your own QGIS server via the `"url"` parameter.
More information about the configuration: https://github.com/qgis/qwc2-demo-app/blob/master/doc/src/qwc_configuration.md

**Comment by fr111** [comment]
Hello danceb,

Thank you for you help.

Regards,

**Comment by danceb** [comment]
You are welcome, hope it helps!
