### ISSUE TITLE
SwitchBackground function button

### ISSUE THREAD

**Issue by shapley** [qgis/qwc2-demo-app#476]
Hi,

Trying to set up the background layers to appear alongside the missing 'SwitchBackground' button in the 'qwc2-demo-app' static website version but cannot see what is wrong. Below is the 'backgroundLayers' part of 'themesConfig.json. Perhaps this is only functional in 'qwc-services'? What other json files require amending/checking if any.

                "backgroundLayers":[
                      {
                          "name":"layer1",
                          "title":"O'S Road Map",
                          "resource": "wmts:https://layer1serviceurl#layername",
                          "thumbnail":"img/mapthumbs/default.jpg",
                          "overview":false
                      },
                      {
                          "name":"layer2",
                          "title":"O'S Leisure Map",
                          "resource": "wmts:https://layer2serviceurl#layername2",
                          "thumbnail":"img/mapthumbs/default.jpg",
                          "overview":true
                      },
                      {
                          "name":"layer3",
                          "title":"APGB 25cm Aerial",
                          "resource": "wms:wmts:https://layer3serviceurl#layername3",
                          "thumbnail":"img/mapthumbs/default.jpg",
                          "overview":false
                      }

],

![backgroundswitcherbutton](https://github.com/qgis/qwc2-demo-app/assets/7022885/d41a2d46-60ee-4d49-9ef4-0a8a20b93719)

**Comment by manisandro** [comment]
You also need to assign the desired backgound layers to a theme, see [https://qwc-services.github.io/configuration/ThemesConfiguration/#manual-theme-configuration or ](https://qwc-services.github.io/configuration/ThemesConfiguration/)

**Comment by shapley** [comment]
I took the code above from within a theme.. These layers are already set up in the QGIS project and configured in QGIS Server. I was hoping to use them in the background switcher too. Can you confirm whether this is possible before I close the call.

**Comment by manisandro** [comment]
Background layers are configured purely client-side and will appear in the background switcher, separate from the layertree. Background layers are typically added to the QGIS project itself just for printing (see https://qwc-services.github.io/topics/Printing/)

**Comment by shapley** [comment]
Ahh...so i need to set up some background layers in the QGIS project which I haven't done then mark them as 'printLayers' under 'backgroundLayers'. Think I've got it.

**Comment by danceb** [comment]
Let me add a hint: 
You don't have to add your background layers to your QGIS projects to use them as print layers! 
This could be a mess, if you have a lot of background layers and many themes and changes with the background layers has to be done in each QGIS project. 

Just set the parameter `printExternalLayers` within the `print-config` in your `config.json` to `true`:
```
      {
        "name": "Print",
        "cfg": {
          "printExternalLayers": true,
          [...]
        },
        "mapClickAction": "identify"
      },
```
See: https://qwc-services.github.io/references/qwc2_plugins/#print

And respective for including them in the raster export:
```
      {
        "name": "RasterExport",
        "cfg": {
          "exportExternalLayers": true,
          [...]
        }
      },
```
See: https://qwc-services.github.io/references/qwc2_plugins/#rasterexport

Then configure the background layer sources within the `backgroundLayers` block in your themesConfig.json/tenantConfig.json:
```
      "backgroundLayers": [
        {
          "name": "background_layer_1",
          "title": "Background Layer 1",
          "group": "Group 1",
          "type": "wms",
          "url": "/your/url",
          "srs": "EPSG:25832",
          "tiled": false,
          "params": {
            "LAYERS": "WMS Layer 1",
            "STYLES": "default"
          },
          "thumbnail": "thumbnail_1.jpg",
          [...]
        },
        [...]
```
And specify them for each theme:
```
        {
          "url": "your/url",
          "title": "Title",
          "backgroundLayers": [
            {
              "name": "background_layer_1",
              "visibility": true
            },
            {
              "name": "background_layer_2"
            },
           [...]
          ],
          [...]
        }
```

Reading the documentation at https://qwc-services.github.io/configuration/ThemesConfiguration/#manual-theme-configuration, it should by possible to specify them within the `defaultBackgroundLayers` block instead of configure them for each theme itself, but I didn't get this to work in my case. But you could have a try.

With this configuration you don't have to add the background layers to each QGIS project to get them printed.
