### ISSUE TITLE
vector style

### ISSUE THREAD

**Issue by luciman** [qgis/qwc2-demo-app#50]
@manisandro Is there any possibility to set/change the style for search result features stile and the identify features, other than changing in qwc2/MapStore2/web/client/components/map/openlayers/plugins/VectorLayer.js

Thank you!

**Comment by manisandro** [comment]
Currently not, but perhaps this could be of interest [1]? Haven't looked at it in detail though.

[1] https://github.com/geosolutions-it/MapStore2/commit/ea6359351936fd8a36ff73106e83fea233b4f9e7

**Comment by luciman** [comment]
The commit above is in geosolutions-it/MapStore2. Can you pull it in sourcepole/MapStore2?
I want to create the possibility to define the style for the searchselection layer and  identifyselection layer either in styleConfig.js or some other place.

**Comment by manisandro** [comment]
Actually some logic is already implemented [1].

[1] https://github.com/sourcepole/MapStore2/blob/master/web/client/plugins/Map.jsx#L79

**Comment by luciman** [comment]
I'll look. For the moment I want to implement different style for searchselection layer and identifyselection layer not for features. I thought the commits from geosolutions-it/MapStore2 will be pulled in sourcepole/MapStore2. 

Do you think it is ok if the styles could be defined styleConfig.js? or should I create another file?

**Comment by manisandro** [comment]
I think styleConfig.json should work fine!

About geosolutions-it/MapStore2 vs sourcepole/MapStore2: sourcepole/MapStore2 hasn't been rebased to upstream in a while, there were some conflicts between our branch and upstream which blocked rebasing, though I think the particular conflict which we hit at the time has since been solved. I'll need to check. Still, if there are particular commits which are useful, it is clearly possible to cherry-pick them.

**Comment by manisandro** [comment]
The default style can now be configured in `config.json`.
