### ISSUE TITLE
Installing QWC2 by pointing apache server to repository 

### ISSUE THREAD

**Issue by clifftanhy** [qgis/qwc2-demo-app#509]
How can I install QWC2 by downloading just the zip file and configuring the httpd.conf file to use QWC 2?

**Comment by mhaelsig** [comment]
Hi,
due to the variety of solutions, you first follow the documentation in 
<https://qwc-services.github.io/Quickstart>.

If you use qwc2 standalone, you will finally get a /prod directory, which you 
will copy to your web server. The httpd.conf file will point to the chosen 
directory of your web server, but - in addition - contains all necessary 
parameters for QGIS Server <https://docs.qgis.org/3.28/en/docs/server_manual/
index.html>.

Michael

Am Dienstag, 12. Dezember 2023, 00:35:24 CET schrieb clifftanhy:
