### ISSUE TITLE
Layer tree needs functionality to fold/unfold groups

### ISSUE THREAD

**Issue by andreasneumann** [qgis/qwc2-demo-app#9]
Some topics (like a cadastral map, or utility map (gaz, water, electricty, etc.)) have a very large layer tree. For such topics, it would be better if the groups are folded by default and a functionality exists to unfold the selected group.

**Comment by karl-magnus** [comment]
The possibilty to hide parts of the layer tree could be useful too. E.g. we have a cadastral group layer that consist of several layers; parcel areas, borders, texts. But the user just needs to switch the group layer and view it's legend. Then we have specified that the feature info for this group layer comes from a certain layer: the parcel layer.

**Comment by manisandro** [comment]
folding/unfolding is implemented in qgis/qwc2@fcc8524b4155b9ce77374fd231dd4a5b0b084170 . Currently everything is expanded by default. Since QGIS Server does not expose the project layer-tree expanded/collapsed state in the GetProjectSettings reply, there is no way to currently replicate the state of the QGIS project layertree. QWCI seems to (maybe optionally?) initially collapse all groups beyond the first level, so perhaps one could generalize this and add a per-theme configuration option 

    "collapseGroupsBelowLevel": <level>

Or one could extend QGIS Server...

**Comment by andreasneumann** [comment]
That proposal sounds fine with me.

I think we don't need to transport this setting from the QGIS project, as it is quite likely that - by accident - one expands layers unwanted. It is safer to collapse everything beyond first level and potentially override on a per theme basis where necessary in the themesConfig.json

**Comment by karl-magnus** [comment]
Agree.

**Comment by manisandro** [comment]
Implemented in qgis/qwc2@14bc58d
