### ISSUE TITLE
Provide central config for enabling/disenabling plugins

### ISSUE THREAD

**Issue by bstroebl** [qgis/qwc2-demo-app#93]
I thought that by disenabling plugins in js/appConfig.js the plugins are disabled in the GUI, too, but the tools still has entries for them (e.g. redlining) ,which are defunct of cours because the plugins are not compiled in the app.

**Comment by manisandro** [comment]
You also need to remove the corresponding menu and/or toolbar entries in the TopBar configuration in config.json. This cannot really be done automatically because a user is free to choose whether to add a corresponding entry to either the menu or the toolbar or both, and perhaps also separately for desktop and mobile mode.

**Comment by bstroebl** [comment]
OK, I see. Would be nice to have nevertheless: if a plugin is not present IMHO it doesn't make sense to have corresponding entries in the GUI. But configuring at two places isn't that much of a a hassle and to automatically deactivate GUI parts maybe is :-)
